# Generated by Django 4.2.20 on 2025-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
    ]
