# Generated by Django 4.2.20 on 2025-04-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductRamki',
        ),
    ]
