# Generated by Django 4.2.20 on 2025-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0004_rename_product_productramki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productramki',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
