# Generated by Django 4.2.20 on 2025-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0005_alter_productramki_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productramki',
            name='price',
            field=models.FloatField(),
        ),
    ]
