# Generated by Django 4.2.20 on 2025-04-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
