# Generated by Django 4.2.20 on 2025-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycenter', '0008_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
